# Generated by Django 6.0.6 on 2026-06-14 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.CharField(blank=True, max_length=20, null=True)),
                ('txn_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('firm', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('asin', models.CharField(blank=True, max_length=100, null=True)),
                ('fsn', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('order_qty', models.IntegerField(default=0)),
                ('order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
