# Generated by Django 6.0.6 on 2026-06-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnVisibilityPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(default='user_view_policy', max_length=50, unique=True)),
                ('show_txn_detail', models.BooleanField(default=True)),
                ('show_merchant_id', models.BooleanField(default=True)),
                ('show_asin', models.BooleanField(default=True)),
                ('show_fsn', models.BooleanField(default=True)),
                ('show_unit_price', models.BooleanField(default=True)),
                ('show_order_amount', models.BooleanField(default=True)),
                ('show_payment_amount', models.BooleanField(default=True)),
            ],
        ),
    ]
