# Generated by Django 6.0.6 on 2026-06-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0002_columnvisibilitypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_firm',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_merchant',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_model_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_model_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_month',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_order_id',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_order_qty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_txn_date',
            field=models.BooleanField(default=True),
        ),
    ]
