# Generated by Django 6.0.6 on 2026-06-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0003_columnvisibilitypolicy_show_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columnvisibilitypolicy',
            old_name='show_asin',
            new_name='show_asin_fsn',
        ),
        migrations.RenameField(
            model_name='columnvisibilitypolicy',
            old_name='show_fsn',
            new_name='show_card_offer',
        ),
        migrations.RenameField(
            model_name='orderreport',
            old_name='asin',
            new_name='asin_fsn',
        ),
        migrations.RemoveField(
            model_name='orderreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderreport',
            name='fsn',
        ),
        migrations.RemoveField(
            model_name='orderreport',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_order_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='card_offer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderreport',
            name='order_status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Partially Delivered', 'Partially Delivered'), ('Cancelled', 'Cancelled')], default='Delivered', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderreport',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
