# Generated by Django 6.0.6 on 2026-06-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0005_firm_location_merchant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin_fsn', models.CharField(max_length=100, unique=True)),
                ('model_name', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_polyshri', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_rio', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_ne', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_sms', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_smmpl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
