# Generated by Django 6.0.6 on 2026-06-20 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0006_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
