# Generated by Django 6.0.6 on 2026-06-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0007_alter_orderreport_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('firm', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('asin_fsn', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_no', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('order_qty', models.IntegerField(default=1)),
                ('order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_qty', models.IntegerField()),
                ('invoice_amount', models.IntegerField()),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('seller_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_gstn', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_status', models.CharField(default='Pending', max_length=50)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
