# Generated by Django 6.0.6 on 2026-06-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0008_invoiceshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_delivery_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_delivery_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_invoice_amount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_invoice_date',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_invoice_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_invoice_qty',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_seller_gstn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='columnvisibilitypolicy',
            name='show_seller_name',
            field=models.BooleanField(default=True),
        ),
    ]
