# Generated by Django 6.0.6 on 2026-06-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0010_alter_invoiceshipment_asin_fsn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderreport',
            name='order_status',
            field=models.CharField(blank=True, default='Open', max_length=50, null=True),
        ),
    ]
