# Generated by Django 6.0.6 on 2026-06-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0011_alter_orderreport_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('asin_fsn', models.CharField(max_length=100)),
                ('short_qty', models.IntegerField(default=0)),
                ('short_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('inward_qty', models.IntegerField(default=0)),
                ('inward_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('asin_fsn', models.CharField(max_length=100)),
                ('refund_qty', models.IntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
