# Generated by Django 6.0.6 on 2026-06-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0012_inwardrecord_refundrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderreport',
            unique_together={('order_id', 'asin_fsn')},
        ),
    ]
