# Generated by Django 6.0.6 on 2026-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_reports', '0013_alter_orderreport_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceshipment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
